from openai import OpenAI
import os

api_key = os.getenv('OPENAI_API_KEY')

client = OpenAI()

def get_openai_response(conversation):
    """
    Sends a prompt to OpenAI and returns the response.
    :param conversation:  Conversation - The conversation object (to remember the context).
    :return: str - The text generated by OpenAI.
    """
    try:
        messages = []
        for msg in conversation.messages:
            messages.append({"role": msg.role, "content": msg.text})

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=messages
        )
        return response.choices[0].message.content.strip()
    except Exception as e: #TODO: handle it in production
        print(f"An error occurred: {e}")
        return None
